### ISSUE TITLE
Database library needs to be explicitly loaded

### ISSUE THREAD

**Issue by graphicalx** [kenjis/ci-phpunit-test#223]
Hi,

Apologize if I'm missing something here, spent a bit of time on this.

I notice that by default Models don't require `$this->load->library('database')`

However, when tests are run, I get this error `Error: Call to a member function query() on null` which seems to get fixed it I call `$this->load->library('database')` explicitly at the start of every model function, which obviously is not ideal.

Please let me know if I'm missing something here.

Thanks!

**Comment by kenjis** [comment]
CodeIgniter's model does not load database by default.
Why you don't require `$this->load->library('database')`?

Would you show me sample code to reproduce it?

**Comment by kenjis** [comment]
When you run your CodeIgniter app via web, it runs only once and exit.
But when you run your tests, CodeIgniter runs so many times.
When testing, you may run many controllers in one (PHP) process.

CodIgniter's autoload runs when a controller is created.
And you know, if you load libs/models once, the CodeIgniter instance has the objects.
If you load Ion-auth once, the CodeIgniter instance has the objects forever.

When you do unit testing, it is very bad news. Because each test should be
isolated. If not, a previous test may change the next test result.

ci-phpunit-test has a way to reset the CodeIgniter instance to isolate each test.
See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#reset-codeigniter-object> for the detail.

And has many methods using `reset_instance()` inside.
Once the CodeIgniter instance is reset, all the loaded libs/models is gone.

So you have to load libraries manually.

If you app depends on database heavily, I recommend you set autoload libraries `database`.

**Comment by graphicalx** [comment]
Cool, thank you for this awesome library!

**Comment by graphicalx** [comment]
One more thing, I'm using Mock_Libraries_Email and so I'm doing this:
```
$this->request->setCallable(function($CI){
            $this->CI->email = new Mock_Libraries_Email();
        });
```
This works fine in a normal case, but in my case, my controllers call a sendEmail function in my library GLib.php
This library loads email like `$this->load->library('email');`
And I feel that line is causing problems. If i remove `$this->load->library('email');`, everything works fine.

Why is this so?

**Comment by kenjis** [comment]
@graphicalx 
`$this->CI->email = new Mock_Libraries_Email();` is called after your controller is instantiated.
If you load library Email after that, `$this->email` would be overridden.

If you put `$this->load->library('email');` in your controller constructor, does not it work?

**Comment by graphicalx** [comment]
Ah ok.
I can't move it to a controller, because a number of places call this library only.

Moved it to
`if (ENVIRONMENT == "production") {`
and its working. I only need it for production. For development i make it write down in a log.

Thanks!
