### ISSUE TITLE
Mock Codeigniter-restserver method

### ISSUE THREAD

**Issue by serazoli** [kenjis/ci-phpunit-test#53]
Hi
Sorry for my stupid question. 
How mock REST_Controller _detect_api_key method to return true.
Thanks

**Comment by kenjis** [comment]
How about this?

~~~php
MonkeyPatch::patchMethod('REST_Controller', ['_detect_api_key' => true]);
~~~

See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#patching-methods-in-user-defined-classes

**Comment by serazoli** [comment]
Many thanks.
I thinking about mock and it did not come to my mind the patch.
Many thanks again

**Comment by kenjis** [comment]
You can't use mocks like this: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#request-and-use-mocks

Because `REST_Controller` is not a dependency of your controller under test.
Your controller extends `REST_Controller`, so if you make a mock object, you must mock the controller under test. And you have to write pure unit test to the mock object (controller).

I don't know we can write pure unit tests for our REST Controller. Because we can't use `$this->request()` (the method can't run mock controller). And we can't use related methods like `$this->assertResponseCode()`, too.

Probably it is very hard to write such tests, even if we can.

**Comment by kenjis** [comment]
I added documentation: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#request-and-use-monkey-patching

**Comment by serazoli** [comment]
The patching method  is good but a little bit slower. That is not problem now.
Thanks.

**Comment by kenjis** [comment]
Yes, it is a only? bad thing of monkey patching.
