### ISSUE TITLE
Mocking or Doubling the MY_Controller

### ISSUE THREAD

**Issue by PhoenixFnX** [kenjis/ci-phpunit-test#65]
I have some supermethods in the MY_Controller class.
For example the `getCurrentAppID()` which returns the application ID the user is working on. I want to Mock that method to make it return 218 for example.

How to do that ? I tried to double the MY_Controller class but unsuccessfully.

**Comment by kenjis** [comment]
How about mocking your controller, not `MY_Controller`?

**Comment by PhoenixFnX** [comment]
Yes that would do the job as my controller extends `MY_Controller` and I could mock the controller functions and properties.
But how can I do that, this looks the same problem to me, If I try to get a double, it will reinstanciate my controller then construct a new `MY_Controller` then construct a new `Controller` which fails....

**Comment by kenjis** [comment]
If you want functional testing, try monkey patching: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#patching-methods-in-user-defined-classes

**Comment by cigzigwon** [comment]
In CI you are using a base controller with a public method. Bad practice for use case. This is because classes extending the controller can access the method as protected and thusly does not need to be tested because of the change in scope. Is there a reason to instantiate the controller externally to get the appId? If so why?

**Comment by kenjis** [comment]
If you have still any question, please create another issue.
