### ISSUE TITLE
$this->input->get_request_header() returns the first header value for all tests

### ISSUE THREAD

**Issue by esetnik** [kenjis/ci-phpunit-test#92]
`$this->input->get_request_header` is not working properly with `$this->request->setHeader()`. It works initially for the first test, but returns the original value for subsequent tests even if those tests update the header value.

**Comment by esetnik** [comment]
https://github.com/kenjis/ci-app-for-ci-phpunit-test/pull/2

**Comment by kenjis** [comment]
It seems we can write once to `$headers`, because it is static. 

How about this fix?

~~~diff
--- a/application/tests/_ci_phpunit_test/replacing/core/Input.php
+++ b/application/tests/_ci_phpunit_test/replacing/core/Input.php
@@ -814,7 +814,7 @@ class CI_Input {
         */
        public function get_request_header($index, $xss_clean = FALSE)
        {
-               static $headers;
+//             static $headers;
 
                if ( ! isset($headers))
                {
~~~

**Comment by kenjis** [comment]
Pushed to `master`: https://github.com/kenjis/ci-phpunit-test/commit/df5edeb1222da24be45becb48bbc045fd8d91466

**Comment by esetnik** [comment]
That looks like it should work well. Thanks!
